# -*- coding: utf-8 -*-
"""Cancer_Pred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13T3jPEtNVFoF0LSq5gTBhciGA9lP8Gg3
"""

import pandas as pd

df = pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/Cancer.csv')

df.head()

df.isnull().sum()

df.columns

y = df['diagnosis']

x = df.drop(['id','diagnosis','Unnamed: 32'],axis=1)

x.shape

df.shape

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=2529)

from sklearn.linear_model import LogisticRegression
md = LogisticRegression(max_iter=500)

md.fit(x_train,y_train)

md.coef_

md.intercept_

y_p = md.predict(x_test)

y_p

from sklearn.metrics import accuracy_score,classification_report

accuracy_score(y_test,y_p)

classification_report(y_test,y_p)



