# -*- coding: utf-8 -*-
"""Fishweight_pred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hoZqXHKJr_NTPJ_8d-1tIhX3NtEBE1Qy
"""

import pandas as pd

df = pd.read_csv('https://github.com/ybifoundation/Dataset/raw/main/Fish.csv')

df.head()

df.isnull().sum()

df.shape

df.columns

y = df['Weight']

x = df[['Category','Height', 'Width', 'Length1',
       'Length2', 'Length3']]

x.shape

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=2529)

from sklearn.linear_model import LinearRegression
model=LinearRegression()

model.fit(x_train,y_train)

model.coef_

model.intercept_

y_pred = model.predict(x_test)

y_test

y_pred

from sklearn.metrics import mean_absolute_error,mean_absolute_percentage_error,r2_score

mean_absolute_error(y_test,y_pred)

r2_score(y_test,y_pred)

