# -*- coding: utf-8 -*-
"""Salaryprediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11I0p2PF7N1H6bUdrFObqUpsvmJhJAbem
"""

import pandas as pd

df = pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/Salary%20Data.csv')

df.head()

df.info()

df.describe()

df.columns

y = df['Salary']
x = df[['Experience Years']]

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y, random_state = 2920)

from sklearn.linear_model import LinearRegression
md = LinearRegression()

md.fit(x_train, y_train)

md.intercept_

md.coef_

y_pred= md.predict(x_test)

print(y_pred)

y_test

from sklearn.metrics import mean_absolute_percentage_error

mean_absolute_percentage_error(y_pred,y_test)

